version: '3.7'
services:
  client:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: stack-overflow-assignment
    container_name: stack-overflow-assignment-container
    command: npm start
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

volumes:
  web-root:
    driver: local
